### ISSUE TITLE
not production ready

### ISSUE THREAD

**Issue by musicformellons** [mapzen/vagrant-tiles#1]
You state:
"This is not meant to be production ready, but merely a demonstration of how the various pieces of an OpenStreetMap vector tile service can fit together."

Could you maybe be a bit more specific what would be needed to make a vector tile server 'production ready'? Thanks!

**Comment by rmarianski** [comment]
Just the usual concerns for any service going to production. I don't think there's anything specific to tiles from that perspective.

That comment was just meant as a caveat that we don't encourage setting up a production environment to mirror the vagrant image.

**Comment by musicformellons** [comment]
Ok, so mainly security concerns I suppose then?

**Comment by rmarianski** [comment]
And redundancy, monitoring, scalability, backups, etc.

**Comment by musicformellons** [comment]
Ok, that's clear. Thanks.
